steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/obudu', '.' ]
# push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/obudu']
# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'demoshop', '--image', 'gcr.io/$PROJECT_ID/obudu', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']