steps:
  # build the container images
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/mercuriemart/obudu:dev
    - --cache=true
    - --cache-ttl=2h
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'obudu', '--image', 'gcr.io/mercuriemart/obudu:dev', '--region', 'us-central1', '--platform', 'managed']
options:
  machineType: 'N1_HIGHCPU_8'