steps:
  # Download .env file
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "gs://mercuriemartstorage/.env", "."]
  # build the container images
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/mercuriemart/customiser:dev
    # - --cache=true
    # - --cache-ttl=6h
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'customiser', '--image', 'gcr.io/mercuriemart/customiser:dev', '--region', 'us-central1', '--platform', 'managed']
options:
  machineType: 'N1_HIGHCPU_8'
