steps:
    # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/obudu:dev', '.' ]
  # push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/obudu:dev']
  # deploy
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'obudu', '--image', 'gcr.io/mercuriemart/obudu:dev', '--region', 'us-central1', '--platform', 'managed']
options:
  machineType: 'N1_HIGHCPU_8'
