FROM nginx:alpine

# Install npm and node
RUN apk add --update yarn
RUN apk add --update npm

# Add bash
RUN apk add --no-cache bash

# install python
RUN apk add --update \
    python \
    util-linux \
    python-dev \
    py-pip \
    build-base \
&& pip install virtualenv \
&& rm -rf /var/cache/apk/*

WORKDIR /app

COPY package.json ./

RUN yarn global add @gridsome/cli
# RUN npm install --global @gridsome/cli

RUN rm -rf node_modules

RUN yarn

RUN yarn run build

COPY . .

# # Make our shell script executable
# RUN chmod +x start.sh

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY /app/dist/. /usr/share/nginx/html/

CMD ["/bin/bash", "-c", "nginx -g 'daemon off;'"]
