const state = {
    styles : {
        storeName: 'Mercuriemart',
        themeColor: '#007bff',
        priColor: '#007bff',
        secColor: '#007bff',
        priFont: "fontPriLato",
        secFont: "fontSecLato",
        navShow: true,
        navLayout: 1,
        navType: "navFixed",
        navLogoImg: false,
        navLogoTextColor: '#fff',
        navLogoTextSize: 100,
        navLogo: 'https://res.cloudinary.com/mercurie/image/upload/v1567432684/mercuriemart/logo.svg',
        cartShow: false,
        loginShow: false,
        heroShow: true,
        heroLayout: 1,
        heroHeight: 300,
        heroBgImgShow: true,
        heroBgImg: 'https://cdn.shopify.com/s/files/1/1724/2825/files/20190304_103547_2000x2000.jpg',
        heroOverlay: "heroOverlay",
        heroColor: '#007bff',
        heroTitle: 'Black Friday Sales',
        heroTitleColor: '#000',
        heroContent: 'Enjoy up to 50% off this season',
        heroContentColor: '#000',
        heroCTA: 'Shop Now',
        heroCTALink: '#',
        heroImage: 'https://via.placeholder.com/500x300',
        heroImageShow: true,
        heroBtnPri: '#007bff',
        heroBtnSec: '#fff',
        collectionShow: true,
        collectionLayout: 1,
        collectionBtnColor: '#fff',
        collectionOneShow: true,
        collectionOneBg: '#eee',
        collectionOneTitle: 'Shoes',
        collectionOneSubtitle: 'New Collection',
        collectionOneImg: 'https://res.cloudinary.com/mercurie/image/upload/v1576348551/mercuriemart/bag.png',
        collectionOneBtn: 'Shop Now',
        collectionOneLink: '#', 
        collectionTwoShow: true,
        collectionTwoBg: '#eee',
        collectionTwoTitle: 'Bags',
        collectionTwoSubtitle: 'New Collection',
        collectionTwoImg: 'https://via.placeholder.com/120',
        collectionTwoBtn: 'Shop Now',
        collectionTwoLink: '#', 
        collectionThreeShow: true,
        collectionThreeBg: '#eee',
        collectionThreeTitle: 'Clothes',
        collectionThreeSubtitle: 'New Collection',
        collectionThreeImg: 'https://via.placeholder.com/120',
        collectionThreeBtn: 'Shop Now',
        collectionThreeLink: '#', 
        productTitleShow: true,
        productTitleLayout: 1,
        productTitleBgColor: '#fff',
        productTitleMain: 'New Arrivals',
        productTitleMainColor: '#000',
        productTitleSub: 'Only the latest...',
        productTitleSubColor: '#000',
        productShow: true,
        productLayout: 1,
        productBg: '#fff',
        notificationShow: true,
        notificationLayout: 1,
        notificationPri: '#222',
        notificationSec: '#fff',
        notificationTitle: 'Get 50% Off Today Only',
        notificationContent: 'Hurry! Sales starts at 10:00AM',
        notificationButton: 'Shop Now',
        notificationButtonPri: '#fff',
        notificationButtonSec: '#222',
        newsletterShow: true,
        newsletterLayout: 1,
        footerShow: true,
        footerLayout: 1,
        subfooterShow: true,
        subfooterLayout: 1
    },
    
    store: null

};

export default state;