const state = {
    styles : {
        storeName: 'storename',
        themeColor: '#007bff',
        priColor: '#007bff',
        secColor: '#007bff',
        priFont: "fontPriLato",
        secFont: "fontSecLato",
        navShow: true,
        navLayout: 1,
        navType: "navFixed",
        navLogoImg: false,
        navLogoTextColor: '#2323',
        navLogoTextSize: 20,
        navLogo: 'https://res.cloudinary.com/mercurie/image/upload/v1567432684/mercuriemart/logo.svg',
        cartShow: false,
        loginShow: false,
        heroShow: true,
        heroLayout: 2,
        heroHeight: 450,
        heroBgImgShow: false,
        heroBgImg: 'https://via.placeholder.com/1000x400',
        heroOverlay: "heroOverlay",
        heroColor: '#b3e4fc',
        heroTitle: 'Welcome to Your Storefront',
        heroTitleColor: '#000',
        heroContent: 'Go go your theme settings to design your storefront',
        heroContentColor: '#000',
        heroCTA: 'Get Started',
        heroCTALink: '#',
        heroImage: 'https://via.placeholder.com/500x300',
        heroImageShow: true,
        heroBtnPri: '#007bff',
        heroBtnSec: '#fff',
        collectionShow: true,
        collectionLayout: 1,
        collectionBtnColor: '#fff',
        collectionOneShow: true,
        collectionOneBg: '#eee',
        collectionOneTitle: 'Collection',
        collectionOneSubtitle: 'New Collection',
        collectionOneImg: 'https://via.placeholder.com/120',
        collectionOneBtn: 'Shop Now',
        collectionOneLink: '#', 
        collectionTwoShow: true,
        collectionTwoBg: '#eee',
        collectionTwoTitle: 'Collection',
        collectionTwoSubtitle: 'New Collection',
        collectionTwoImg: 'https://via.placeholder.com/120',
        collectionTwoBtn: 'Shop Now',
        collectionTwoLink: '#', 
        collectionThreeShow: true,
        collectionThreeBg: '#eee',
        collectionThreeTitle: 'Collection',
        collectionThreeSubtitle: 'New Collection',
        collectionThreeImg: 'https://via.placeholder.com/120',
        collectionThreeBtn: 'Shop Now',
        collectionThreeLink: '#', 
        productTitleShow: true,
        productTitleLayout: 1,
        productTitleBgColor: '#fff',
        productTitleMain: 'New Arrivals',
        productTitleMainColor: '#000',
        productTitleSub: 'Only the latest...',
        productTitleSubColor: '#000',
        productShow: true,
        productLayout: 1,
        productBg: '#fff',
        notificationShow: true,
        notificationLayout: 1,
        notificationPri: '#222',
        notificationSec: '#fff',
        notificationTitle: 'Get 50% Off Today Only',
        notificationContent: 'Hurry! Sales starts at 10:00AM',
        notificationButton: 'Shop Now',
        notificationButtonPri: '#fff',
        notificationButtonSec: '#222',
        newsletterShow: true,
        newsletterLayout: 1,
        footerShow: true,
        footerLayout: 1,
        subfooterShow: true,
        subfooterLayout: 1
    },
    
    store: null

};

export default state;