import store from '../../store/store.js';
import { eventBus } from '@/eventBus.js';

eventBus.$on('themeDefault', () => {

    // Data
    store.commit('setNavLogo', 'https://res.cloudinary.com/mercurie/image/upload/v1567432684/mercuriemart/logo.svg');
    store.commit('setHeroBgImg', 'https://via.placeholder.com/1000x400');
    store.commit('setHeroContent', 'Go go your theme settings to design your storefront');
    store.commit('setHeroTitle', 'Welcome to Your Storefront');
    store.commit('setHeroCTA', 'Get Started');
    store.commit('setHeroCTALink', '/design/');
    store.commit('setHeroImage', 'https://via.placeholder.com/500x300');
    store.commit('setCollectionOneTitle', 'Collection');
    store.commit('setCollectionOneSubtitle', 'New Collection');
    store.commit('setCollectionOneImg', 'https://via.placeholder.com/120');
    store.commit('setCollectionOneBtn', 'Shop Now');
    store.commit('setCollectionOneLink', '#');
    store.commit('setCollectionTwoTitle', 'Collection');
    store.commit('setCollectionTwoSubtitle', 'New Collection');
    store.commit('setCollectionTwoImg', 'https://via.placeholder.com/120');
    store.commit('setCollectionTwoBtn', 'Shop Now');
    store.commit('setCollectionTwoLink', '#');
    store.commit('setCollectionThreeTitle', 'Collection');
    store.commit('setCollectionThreeSubtitle', 'New Collection');
    store.commit('setCollectionThreeImg', 'https://via.placeholder.com/120');
    store.commit('setCollectionThreeBtn', 'Shop Now');
    store.commit('setCollectionThreeLink', '#');
    store.commit('setProductTitleMain', 'New Arrivals');
    store.commit('setProductTitleSub', 'Only the latest...');
    store.commit('setNotificationTitle', 'Get 50% Off Today Only');
    store.commit('setNotificationContent', 'Hurry! Sales starts at 10:00AM');
    store.commit('setNotificationButton', 'Shop Now');

    // Styles
    store.commit('setThemeName', 'Default');
    store.commit('setUnderConstruction', false);
    store.commit('setThemeColor', '#007bff');
    store.commit('setPriColor', '#007bff');
    store.commit('setSecColor', '#007bff');
    store.commit('setPriFont', 'fontPriLato');
    store.commit('setSecFont', 'fontSecLato');
    store.commit('setNavFont', 'fontPriLato');
    store.commit('setNavShow', true);
    store.commit('setNavLayout', 1);
    store.commit('setNavType', 'navFixed');
    store.commit('setNavColor', '#333');
    store.commit('setNavBgColor', '##fff');
    store.commit('setNavLogoImg', false);
    store.commit('setNavLogoTextColor', '#333');
    store.commit('setNavLogoTextSize', 20);
    store.commit('setCartShow', false);
    store.commit('setLoginShow', false);
    store.commit('setHeroShow', true);
    store.commit('setHeroLayout', 2);
    store.commit('setHeroHeight', '450');
    store.commit('setHeroBgImgShow', false);
    store.commit('setHeroColor', '#b3e4fc');
    store.commit('setHeroTitleColor', '#000');
    store.commit('setHeroContentColor', '#000');
    store.commit('setHeroImageShow', true);
    store.commit('setHeroBtnPri', '#007bff');
    store.commit('setHeroBtnSec', '#fff');
    store.commit('setCollectionShow', true);
    store.commit('setCollectionLayout', 2);
    store.commit('setCollectionBgColor', '#fff');
    store.commit('setCollectionBtnColor', '#fff');
    store.commit('setCollectionTextColor', '#fff');
    store.commit('setCollectionOneShow', true);
    store.commit('setCollectionOneBg', '#eee');
    store.commit('setCollectionTwoShow', true);
    store.commit('setCollectionTwoBg', '#eee');
    store.commit('setCollectionThreeShow', true);
    store.commit('setCollectionThreeBg', '#eee');
    store.commit('setProductTitleShow', true);
    store.commit('setProductTitleLayout', 1);
    store.commit('setProductTitleBgColor', '#fff');
    store.commit('setProductTitleMainColor', '#333');
    store.commit('setProductTitleSubColor', '#333');
    store.commit('setProductShow', true);
    store.commit('setProductLayout', 1);
    store.commit('setProductBg', '#fff');
    store.commit('setNotificationShow', false);
    store.commit('setNotificationLayout', 1);
    store.commit('setNotificationPri', '#333');
    store.commit('setNotificationSec', '#fff');
    store.commit('setNotificationButtonPri', '#fff');
    store.commit('setNotificationButtonSec', '#333');
    store.commit('setNewsletterShow', false);
    store.commit('setNewsletterLayout', 1);
    store.commit('setFooterShow', false);
    store.commit('setFooterLayout', 1);
    store.commit('setSubfooterShow', true);
    store.commit('setSubfooterLayout', 1);
    store.commit('setSubfooterBgColor', '#fff');
    store.commit('setSubfooterColor', '#333');
    console.log(`Theme successfully changed to Default`);
});
